version: '3.1'

services:
  mysqldb:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./database/initial_script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/T_ONTIME_MARKETING.csv:/var/lib/mysql-files/T_ONTIME_MARKETING.csv
      - ./database/L_UNIQUE_CARRIERS.csv:/var/lib/mysql-files/L_UNIQUE_CARRIERS.csv
    networks:
      - hpc_network
    healthcheck:
      test: ["CMD-SHELL", "exit | mysql -h localhost -P 3306 -u root -p$$MYSQL_ROOT_PASSWORD" ]
      timeout: 10s
      retries: 10

#  spring_app:
#    build:
#      context: ./spark
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    depends_on:
#      mysqldb:
#        condition: service_healthy
#    networks:
#      - hpc_network

networks:
  hpc_network:
    driver: bridge