version: '3.1'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 0B1g1VIpLFVo
    ports:
      - "3306:3306"
    volumes:
      - ./database/initial_script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/T_ONTIME_MARKETING.csv:/var/lib/mysql-files/T_ONTIME_MARKETING.csv