version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - ./database/initial_script.sql:/docker-entrypoint-initdb.d/init.sql
      - ./database/T_ONTIME_MARKETING.csv:/var/lib/mysql-files/T_ONTIME_MARKETING.csv
      - ./database/L_UNIQUE_CARRIERS.csv:/var/lib/mysql-files/L_UNIQUE_CARRIERS.csv

#  hbase:
#    image: dajobe/hbase
#    ports:
#      - "16010:16010" # Port for HBase Master web UI

  custom_sqoop:
    build:
      context: .
      dockerfile: SqoopDockerfile
    depends_on:
      - mysql_db
    ports:
    - "16010:16010" # Port for HBase Master web UI
    - "2181:2181"
    - "9000:9000"
    environment:
      - HBASE_HOME=/opt/hbase
      - CLASSPATH=/jdbc/mysql-connector-j.jar:$CLASSPATH
    command: >
      sh -c "
        while ! nc -z mysql_db 3306; do sleep 10; echo 'ping' ; done;
        echo 'ready';
        sleep 100000;
        sqoop import --connect jdbc:mysql://mysql_db:3306/HPC --username root --password root --table airlineAirportData --hbase-table airlines --column-family cf --hbase-create-table --hbase-row-key id"

